version: "3.8" 
services: 
  web: 
    image: nginx:alpine 
    deploy: 
      replicas: 3 
    healthcheck: 
      test: ["CMD", "wget", "-qO", "-", "http://localhost"]  
      interval: 5s 
      timeout: 2s 
      retries: 3 
      start_period: 15s 