apiVersion: v1
kind: Service
metadata:
  labels:
    app: pets
    service: web
  name: web
spec:
  type: NodePort
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    app: pets
    service: web
