apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: pets-data
  name: pets-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      service: web
  template:
    metadata:
      labels:
        service: web
    spec:
      containers:
        - image: fundamentalsofdocker/ch11-web:2.0
          name: web
          ports:
            - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      service: db
  template:
    metadata:
      labels:
        service: db
    spec:
      containers:
        - image: fundamentalsofdocker/ch11-db:2.0
          name: db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pets-data
      volumes:
        - name: pets-data
          persistentVolumeClaim:
            claimName: pets-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: web
  name: web
spec:
  type: NodePort
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    service: web
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: db
  name: db
spec:
  type: NodePort
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    service: db