version: "3.8" 
services: 
  db:
    image: postgres:alpine
    volumes:
    - pg-data:/var/lib/postgresql/data
    - ./db:/docker-entrypoint-initdb.d
  
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  web:
    image: gnschenker/ch11-web:1.0
    depends_on:
    - db

volumes: 
  pg-data:
  pgadmin-data: